name: Deploy Hugo site to S3/Cloudfront

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: peaceiris/hugo
    steps:
      - uses: actions/checkout@v1
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
      - name: Build Hugo
        run: hugo
      - name: Deploy To Prod S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: hugo deploy
